# Generated by Django 2.0.3 on 2018-03-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=20)),
                ('fund_name', models.CharField(max_length=40)),
                ('fund_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FundPara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(max_length=2)),
                ('redeem_per', models.FloatField()),
                ('redeem_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FundTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=20)),
                ('trade_ts', models.DateTimeField()),
                ('fund_nav', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=20)),
                ('trade_ts', models.DateTimeField()),
                ('trade_direction', models.CharField(max_length=1)),
                ('trader', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_account', models.CharField(max_length=20)),
                ('login_pass', models.CharField(max_length=40)),
                ('trader_name', models.CharField(max_length=10)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
