# Generated by Django 2.0.3 on 2018-05-13 01:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=20)),
                ('fund_name', models.CharField(max_length=40)),
                ('fund_type', models.CharField(max_length=2)),
                ('fund_status', models.CharField(default='1', max_length=1)),
                ('fund_total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FundPara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(max_length=2)),
                ('redeem_per', models.FloatField(default=0)),
                ('redeem_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FundTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=20)),
                ('trade_ts', models.DateTimeField()),
                ('fund_nav', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Order', primary_key=True, serialize=False)),
                ('trade_ts', models.DateTimeField()),
                ('trade_direction', models.CharField(choices=[('1', '买'), ('2', '卖')], default='1', max_length=1)),
                ('trading_fee', models.FloatField(default=0)),
                ('trading_share', models.IntegerField(default=0)),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundapp.FundInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_account', models.CharField(max_length=20)),
                ('trader_name', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundapp.Trader'),
        ),
    ]
